language: r
r:
  - bioc-release
sudo: false
cache: packages
jobs:
  include:
    - stage: prepare cache
      script: true
    - stage: test
env:
  global:
    - R_BUILD_ARGS="--no-build-vignettes --no-manual"
    - R_CHECK_ARGS="--no-build-vignettes --no-manual --timings"  ## do not build vignettes or manual
    - _R_CHECK_TIMINGS_="0"  ## get the timing information for the examples for all of your functions
