---
title: "Introduction to MagenSingleCell"
author: "Meng Wang"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette:
  fig_caption: yes
vignette: >
  %\VignetteIndexEntry{Introduction to MagenSingleCell}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```


## Data set

The example data set comes from Ciucci 2018[^1]. Two replicates of CD44+ cells were available from [GSM3423794](https://www.ncbi.nlm.nih.gov/geo/download/?acc=GSM3423794) and [GSM3423795](https://www.ncbi.nlm.nih.gov/geo/download/?acc=GSM3423795). 

```{r}
dir.create("~/Downloads/LMCV")
rep1_path <- GEOquery::getGEOSuppFiles("GSM3423794", baseDir = "~/Downloads/LCMV")
rep2_path <- GEOquery::getGEOSuppFiles("GSM3423795", baseDir = "~/Downloads/LCMV")
file.rename("~/Downloads/LCMV/GSM3423794", "~/Downloads/LCMV/LCMV1")
file.rename("~/Downloads/LCMV/GSM3423795", "~/Downloads/LCMV/LCMV2")
```


```{r initialize}
library(MagenSingleCell)
Exhaustion <- c('Pdcd1','Cd244','Havcr2','Ctla4','Cd160','Lag3','Tigit','Cd96')
env <- initialize.project(datasets = c("LCMV1", "LCMV2"), 
                          origins = rep("CD44+ cells", 2),
                          experiments = c("Rep1", "Rep2"),
                          data.path = "~/Downloads/LCMV",
                          work.path = "~/Downloads/LCMV_analysis",
                          marker.genes = unique(marker_genes$symbol))
```

## Read data

The `read.data` function reads the data in 10X genomics format (`matrix.mtx`, `gene.tsv`, `barcode.tsv`)

```{r}
env <- read.data(env, subsample = 1000)
```

## Preprocess data

```{r}
env <- get.variable.genes(env) 
env <- add.confounder.variables (env,
	ribosomal.score = ribosomal.score(env),
	mitochondrial.score = mitochondrial.score(env),
	cell.cycle.score = cell.cycle.score(env),
	Exhaustion = controlled.mean.score(env, Exhaustion))

```

## PCA

```{r}
env <- MagenSingleCell::PCA(env)
```

## clustering

```{r}
env <- cluster.analysis(env)
```

## Differential expression and visualizations



[^1] Ciucci, Thomas, et al. "The Emergence and Functional Fitness of Memory CD4+ T Cells Require the Transcription Factor Thpok." _Immunity_ 50.1 (2019): 91-105.